install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
before script:
  - rm -rf public
script:
  - hugo version
  - hugo
env:
  global:
    - PRODUCTION=true
    - HUGO_RELEASE=0.77.0
branches:
  only:
    - master
